<a href="https://colab.research.google.com/github/Vaju12345/spring-petclinic/blob/main/Internship_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded=files.upload()

Saving SkyCity Auckland Restaurants & Bars.csv to SkyCity Auckland Restaurants & Bars.csv

In [2]:
import pandas as pd
df=pd.read_csv(list(uploaded.keys())[0])
df.head()

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,DeliveryCostPerOrder,SD_DeliveryTotalCost,InStoreNetProfit,UberEatsNetProfit,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,3.25,458.25,3682.14,1352.45,752.78,2177.19,0.42,0.45,0.25,0.3
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,4.72,1600.08,3605.72,1318.61,731.99,3119.38,0.23,0.45,0.25,0.3
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,3.25,1163.50,7810.95,1555.90,863.42,4172.99,0.44,0.45,0.25,0.3
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,0.89,231.40,2546.02,-72.25,-40.20,2833.26,0.25,0.45,0.25,0.3
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,2.66,774.06,3093.09,226.17,125.53,2674.56,0.27,0.45,0.25,0.3

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1696 entries, 0 to 1695
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CuisineType            1696 non-null   object
 1   RestaurantID           1696 non-null   int64
 2   RestaurantName         1696 non-null   object
 3   Segment                1696 non-null   object
 4   Subregion              1696 non-null   object
 5   GrowthFactor           1696 non-null   float64
 6   AOV                    1696 non-null   float64
 7   MonthlyOrders          1696 non-null   int64
 8   InStoreOrders          1696 non-null   int64
 9   InStoreRevenue         1696 non-null   float64
 10  UberEatsOrders         1696 non-null   int64
 11  DoorDashOrders         1696 non-null   int64
 12  SelfDeliveryOrders     1696 non-null   int64
 13  UberEatsRevenue        1696 non-null   float64
 14  DoorDashRevenue        1696 non-null   float64
 15  SelfDeliveryRevenue    1696 non-null   float64
 16  COGSRate               1696 non-null   float64
 17  OPEXRate               1696 non-null   float64
 18  CommissionRate         1696 non-null   float64
 19  DeliveryRadiusKM       1696 non-null   int64
 20  DeliveryCostPerOrder   1696 non-null   float64
 21  SD_DeliveryTotalCost   1696 non-null   float64
 22  InStoreNetProfit       1696 non-null   float64
 23  UberEatsNetProfit      1696 non-null   float64
 24  DoorDashNetProfit      1696 non-null   float64
 25  SelfDeliveryNetProfit  1696 non-null   float64
 26  InStoreShare           1696 non-null   float64
 27  UE_share               1696 non-null   float64
 28  DD_share               1696 non-null   float64
 29  SD_share               1696 non-null   float64
dtypes: float64(19), int64(7), object(4)
memory usage: 397.6+ KB

In [5]:
df.describe()

,RestaurantID,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,UberEatsOrders,DoorDashOrders,SelfDeliveryOrders,UberEatsRevenue,...,DeliveryCostPerOrder,SD_DeliveryTotalCost,InStoreNetProfit,UberEatsNetProfit,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share
count,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,...,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000,1696.000000
mean,25848.500000,1.028255,38.516887,1190.527123,218.980542,8422.392730,471.906250,257.155071,242.485259,18170.030360,...,3.119363,755.783886,2257.321557,152.410425,89.105100,2139.315118,0.225654,0.486763,0.265242,0.247995
std,489.737345,0.022700,4.459408,422.334848,149.758619,5851.233352,171.781981,92.605301,129.950736,6959.241673,...,1.344848,541.323056,1618.692119,2340.125579,1271.832584,1875.802610,0.126977,0.067685,0.034294,0.094582
min,25001.000000,0.990000,29.790000,441.000000,13.000000,412.360000,142.000000,81.000000,60.000000,5050.950000,...,0.890000,53.400000,155.000000,-7787.110000,-4349.940000,-983.280000,0.030000,0.350000,0.200000,0.150000
25%,25424.750000,1.030000,34.787500,827.000000,101.000000,3904.342500,331.000000,179.750000,146.000000,12524.745000,...,1.770000,358.662500,1122.580000,-1291.512500,-718.617500,807.867500,0.110000,0.450000,0.250000,0.150000
50%,25848.500000,1.040000,38.340000,1182.000000,178.000000,6791.430000,456.000000,249.000000,212.000000,17548.980000,...,3.250000,601.800000,1785.720000,676.685000,369.665000,1742.945000,0.210000,0.500000,0.250000,0.200000
75%,26272.250000,1.050000,42.495000,1525.000000,307.000000,11550.755000,602.000000,326.250000,306.250000,23016.000000,...,4.130000,1005.030000,2848.090000,1581.570000,862.602500,2995.282500,0.320000,0.550000,0.300000,0.300000
max,26696.000000,1.050000,47.230000,2337.000000,819.000000,35356.230000,937.000000,466.000000,702.000000,43038.960000,...,5.310000,3653.280000,10474.680000,8275.570000,4514.880000,13222.100000,0.550000,0.600000,0.300000,0.450000

In [6]:
df.isnull().sum()

CuisineType              0
RestaurantID             0
RestaurantName           0
Segment                  0
Subregion                0
GrowthFactor             0
AOV                      0
MonthlyOrders            0
InStoreOrders            0
InStoreRevenue           0
UberEatsOrders           0
DoorDashOrders           0
SelfDeliveryOrders       0
UberEatsRevenue          0
DoorDashRevenue          0
SelfDeliveryRevenue      0
COGSRate                 0
OPEXRate                 0
CommissionRate           0
DeliveryRadiusKM         0
DeliveryCostPerOrder     0
SD_DeliveryTotalCost     0
InStoreNetProfit         0
UberEatsNetProfit        0
DoorDashNetProfit        0
SelfDeliveryNetProfit    0
InStoreShare             0
UE_share                 0
DD_share                 0
SD_share                 0
dtype: int64

In [7]:
df["MonthlyOrders"].value_counts()

MonthlyOrders
1361    6
1561    6
1299    6
1525    5
799     5
       ..
1349    1
1354    1
572     1
612     1
800     1
Name: count, Length: 1024, dtype: int64

In [8]:
df["GrowthFactor"].value_counts()

GrowthFactor
1.04    462
1.05    441
0.99    410
1.03    383
Name: count, dtype: int64

In [9]:
df["AOV"].value_counts()

AOV
32.39    7
36.32    6
39.35    5
41.47    5
44.39    5
        ..
39.99    1
31.74    1
38.63    1
33.68    1
39.50    1
Name: count, Length: 1064, dtype: int64

In [11]:
df["Demand_level"]=pd.cut(df["MonthlyOrders"],bins=[0,500,2000,5000],labels=["Low","medium","high"])
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,SD_DeliveryTotalCost,InStoreNetProfit,UberEatsNetProfit,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share,Demand_level
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,458.25,3682.14,1352.45,752.78,2177.19,0.42,0.45,0.25,0.3,medium
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,1600.08,3605.72,1318.61,731.99,3119.38,0.23,0.45,0.25,0.3,medium
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,1163.50,7810.95,1555.90,863.42,4172.99,0.44,0.45,0.25,0.3,medium
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,231.40,2546.02,-72.25,-40.20,2833.26,0.25,0.45,0.25,0.3,medium
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,774.06,3093.09,226.17,125.53,2674.56,0.27,0.45,0.25,0.3,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,456.82,746.46,2356.69,1416.08,1734.40,0.07,0.50,0.30,0.2,Low
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,898.58,1338.12,3720.20,2230.45,2964.70,0.07,0.50,0.30,0.2,medium
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,205.72,969.04,459.09,275.72,1966.80,0.09,0.50,0.30,0.2,medium
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,284.16,1585.72,1168.16,700.90,2171.15,0.13,0.50,0.30,0.2,medium
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,974.60,715.79,-3099.92,-1857.69,-127.97,0.17,0.50,0.30,0.2,medium

In [14]:
df["Growth_category"]=df["GrowthFactor"].apply(lambda x:"High Growth" if x>1.2 else "stable" if x>=0.9 else "declining")
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,InStoreNetProfit,UberEatsNetProfit,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share,Demand_level,Growth_category
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,3682.14,1352.45,752.78,2177.19,0.42,0.45,0.25,0.3,medium,stable
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,3605.72,1318.61,731.99,3119.38,0.23,0.45,0.25,0.3,medium,stable
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,7810.95,1555.90,863.42,4172.99,0.44,0.45,0.25,0.3,medium,stable
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,2546.02,-72.25,-40.20,2833.26,0.25,0.45,0.25,0.3,medium,stable
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,3093.09,226.17,125.53,2674.56,0.27,0.45,0.25,0.3,medium,stable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,746.46,2356.69,1416.08,1734.40,0.07,0.50,0.30,0.2,Low,stable
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,1338.12,3720.20,2230.45,2964.70,0.07,0.50,0.30,0.2,medium,stable
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,969.04,459.09,275.72,1966.80,0.09,0.50,0.30,0.2,medium,stable
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,1585.72,1168.16,700.90,2171.15,0.13,0.50,0.30,0.2,medium,stable
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,715.79,-3099.92,-1857.69,-127.97,0.17,0.50,0.30,0.2,medium,stable

In [16]:
df["AOV_level"]=pd.cut(df["AOV"],bins=[0,500,2000,5000],labels=["low","medium","high"])
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,UberEatsNetProfit,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share,Demand_level,Growth_category,AOV_level
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,1352.45,752.78,2177.19,0.42,0.45,0.25,0.3,medium,stable,low
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,1318.61,731.99,3119.38,0.23,0.45,0.25,0.3,medium,stable,low
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,1555.90,863.42,4172.99,0.44,0.45,0.25,0.3,medium,stable,low
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,-72.25,-40.20,2833.26,0.25,0.45,0.25,0.3,medium,stable,low
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,226.17,125.53,2674.56,0.27,0.45,0.25,0.3,medium,stable,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,2356.69,1416.08,1734.40,0.07,0.50,0.30,0.2,Low,stable,low
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,3720.20,2230.45,2964.70,0.07,0.50,0.30,0.2,medium,stable,low
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,459.09,275.72,1966.80,0.09,0.50,0.30,0.2,medium,stable,low
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,1168.16,700.90,2171.15,0.13,0.50,0.30,0.2,medium,stable,low
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,-3099.92,-1857.69,-127.97,0.17,0.50,0.30,0.2,medium,stable,low

In [17]:
df["Growth_Score"] = (
    df["MonthlyOrders"] * 0.4 +
    df["GrowthFactor"] * 1000 * 0.3 +
    df["AOV"] * 0.3
)

In [18]:
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,DoorDashNetProfit,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share,Demand_level,Growth_category,AOV_level,Growth_Score
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,752.78,2177.19,0.42,0.45,0.25,0.3,medium,stable,low,589.391
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,731.99,3119.38,0.23,0.45,0.25,0.3,medium,stable,low,882.335
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,863.42,4172.99,0.44,0.45,0.25,0.3,medium,stable,low,1010.809
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,-40.20,2833.26,0.25,0.45,0.25,0.3,medium,stable,low,753.084
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,125.53,2674.56,0.27,0.45,0.25,0.3,medium,stable,low,817.302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,1416.08,1734.40,0.07,0.50,0.30,0.2,Low,stable,low,517.543
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,2230.45,2964.70,0.07,0.50,0.30,0.2,medium,stable,low,704.660
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,275.72,1966.80,0.09,0.50,0.30,0.2,medium,stable,low,631.616
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,700.90,2171.15,0.13,0.50,0.30,0.2,medium,stable,low,753.694
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,-1857.69,-127.97,0.17,0.50,0.30,0.2,medium,stable,low,835.773

In [20]:
df["Total_Share"] = df["InStoreShare"] + df["UE_share"] + df["DD_share"] + df["SD_share"]
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,SelfDeliveryNetProfit,InStoreShare,UE_share,DD_share,SD_share,Demand_level,Growth_category,AOV_level,Growth_Score,Total_Share
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,2177.19,0.42,0.45,0.25,0.3,medium,stable,low,589.391,1.42
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,3119.38,0.23,0.45,0.25,0.3,medium,stable,low,882.335,1.23
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,4172.99,0.44,0.45,0.25,0.3,medium,stable,low,1010.809,1.44
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,2833.26,0.25,0.45,0.25,0.3,medium,stable,low,753.084,1.25
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,2674.56,0.27,0.45,0.25,0.3,medium,stable,low,817.302,1.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,1734.40,0.07,0.50,0.30,0.2,Low,stable,low,517.543,1.07
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,2964.70,0.07,0.50,0.30,0.2,medium,stable,low,704.660,1.07
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,1966.80,0.09,0.50,0.30,0.2,medium,stable,low,631.616,1.09
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,2171.15,0.13,0.50,0.30,0.2,medium,stable,low,753.694,1.13
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,-127.97,0.17,0.50,0.30,0.2,medium,stable,low,835.773,1.17

In [21]:
df["Dominant_Channel"] = df[["InStoreShare", "UE_share", "DD_share", "SD_share"]].idxmax(axis=1)

In [23]:
df["Channel_Diversity"] = 1 - (
    df[["InStoreShare", "UE_share", "DD_share", "SD_share"]]
    .max(axis=1)
)
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,UE_share,DD_share,SD_share,Demand_level,Growth_category,AOV_level,Growth_Score,Total_Share,Dominant_Channel,Channel_Diversity
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,0.45,0.25,0.3,medium,stable,low,589.391,1.42,UE_share,0.55
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,0.45,0.25,0.3,medium,stable,low,882.335,1.23,UE_share,0.55
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,0.45,0.25,0.3,medium,stable,low,1010.809,1.44,UE_share,0.55
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,0.45,0.25,0.3,medium,stable,low,753.084,1.25,UE_share,0.55
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,0.45,0.25,0.3,medium,stable,low,817.302,1.27,UE_share,0.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,0.50,0.30,0.2,Low,stable,low,517.543,1.07,UE_share,0.50
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,0.50,0.30,0.2,medium,stable,low,704.660,1.07,UE_share,0.50
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,0.50,0.30,0.2,medium,stable,low,631.616,1.09,UE_share,0.50
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,0.50,0.30,0.2,medium,stable,low,753.694,1.13,UE_share,0.50
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,0.50,0.30,0.2,medium,stable,low,835.773,1.17,UE_share,0.50

In [24]:
df["Online_Share"] = df["UE_share"] + df["DD_share"] + df["SD_share"]
df["Offline_Share"] = df["InStoreShare"]

In [28]:
df["Reach_Category"] = pd.cut(df["DeliveryRadiusKM"],
                             bins=[0, 3, 7, 15],
                             labels=["Local", "Medium", "Wide"])
df

,CuisineType,RestaurantID,RestaurantName,Segment,Subregion,GrowthFactor,AOV,MonthlyOrders,InStoreOrders,InStoreRevenue,...,Demand_level,Growth_category,AOV_level,Growth_Score,Total_Share,Dominant_Channel,Channel_Diversity,Online_Share,Offline_Share,Reach_Category
0,Burgers,25731,Urban Burgers House,Cafe,North Shore,1.03,43.97,668,197,8662.09,...,medium,stable,low,589.391,1.42,UE_share,0.55,1.0,0.42,Wide
1,Burgers,25123,Urban Burgers Diner,QSR,South Auckland,1.05,40.45,1388,259,10476.55,...,medium,stable,low,882.335,1.23,UE_share,0.55,1.0,0.23,NaN
2,Burgers,25177,King Burgers Eatery,Cafe,West Auckland,1.04,40.03,1717,524,20975.72,...,medium,stable,low,1010.809,1.44,UE_share,0.55,1.0,0.44,Wide
3,Burgers,25540,Classic Burgers Tavern,QSR,North Shore,1.03,36.28,1083,216,7836.48,...,medium,stable,low,753.084,1.25,UE_share,0.55,1.0,0.25,Local
4,Burgers,25258,Lucky Burgers Bistro,Cafe,South Auckland,1.05,34.34,1230,261,8962.74,...,medium,stable,low,817.302,1.27,UE_share,0.55,1.0,0.27,Wide
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1691,Thai,26412,Lotus Bistro,Ghost Kitchen,North Shore,1.03,45.81,487,31,1420.11,...,Low,stable,low,517.543,1.07,UE_share,0.50,1.0,0.07,NaN
1692,Thai,26275,Dragon Bistro,Ghost Kitchen,North Shore,1.03,44.20,956,62,2740.40,...,medium,stable,low,704.660,1.07,UE_share,0.50,1.0,0.07,NaN
1693,Thai,26454,Dragon Corner,QSR,South Auckland,1.05,44.72,758,62,2772.64,...,medium,stable,low,631.616,1.09,UE_share,0.50,1.0,0.09,Medium
1694,Thai,25699,Golden Corner,Cafe,North Shore,1.03,36.98,1084,124,4585.52,...,medium,stable,low,753.694,1.13,UE_share,0.50,1.0,0.13,Medium
1695,Thai,26388,Lotus Grill,Full-service,West Auckland,1.04,33.91,1284,186,6307.26,...,medium,stable,low,835.773,1.17,UE_share,0.50,1.0,0.17,Wide